# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Devmachine < Formula
  desc "Turn a VPS into workspaces you develop in"
  homepage "https://mydevmachine.sh/"
  version "0.7.28"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mydevmachine/devmachine/releases/download/v0.7.28/devmachine_0.7.28_darwin_amd64.tar.gz"
      sha256 "57444c8bb600ad1fb0c90958014dd5c62cd3322ba5122a26a02fff4800230f66"

      define_method(:install) do
        bin.install "devmachine"
        bin.install_symlink bin/"devmachine" => "advm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mydevmachine/devmachine/releases/download/v0.7.28/devmachine_0.7.28_darwin_arm64.tar.gz"
      sha256 "f3012f158be26e822a1c9ef46bad36be3ca9bf055329ed67de73004fe5a72deb"

      define_method(:install) do
        bin.install "devmachine"
        bin.install_symlink bin/"devmachine" => "advm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mydevmachine/devmachine/releases/download/v0.7.28/devmachine_0.7.28_linux_amd64.tar.gz"
      sha256 "72b251cda43bb8fe56e2d0d5990036e9d5f0687fe602c854961f95bfef546b83"
      define_method(:install) do
        bin.install "devmachine"
        bin.install_symlink bin/"devmachine" => "advm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mydevmachine/devmachine/releases/download/v0.7.28/devmachine_0.7.28_linux_arm64.tar.gz"
      sha256 "ea58621d35e58fde2d984ae0f25aaeaea1b13e977cfc15d29098db63826b64d7"
      define_method(:install) do
        bin.install "devmachine"
        bin.install_symlink bin/"devmachine" => "advm"
      end
    end
  end

  def caveats
    <<~EOS
      Teach your coding agent devmachine (Claude Code, Codex, and others):
        devmachine skills add
      Get started: https://mydevmachine.sh/getting-started/
    EOS
  end

  test do
    system "#{bin}/devmachine", "version"
  end
end
