# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Devmachine < Formula
  desc "Turn a VPS into workspaces you develop in"
  homepage "https://mydevmachine.sh/"
  version "0.7.27"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mydevmachine/devmachine/releases/download/v0.7.27/devmachine_0.7.27_darwin_amd64.tar.gz"
      sha256 "c71c1d1d297bca852fa565b681e1000302f36a27dbfed6db9238c1f23e7592a5"

      define_method(:install) do
        bin.install "devmachine"
        bin.install_symlink bin/"devmachine" => "advm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mydevmachine/devmachine/releases/download/v0.7.27/devmachine_0.7.27_darwin_arm64.tar.gz"
      sha256 "5b7391de80c7972d09abe2b337f88ce1a10f1b63f2e842afc576672f6b0ae2c3"

      define_method(:install) do
        bin.install "devmachine"
        bin.install_symlink bin/"devmachine" => "advm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mydevmachine/devmachine/releases/download/v0.7.27/devmachine_0.7.27_linux_amd64.tar.gz"
      sha256 "c5af230ec5d5ee1a0a78683e7946dc760a7f8d149f22794cbab823ebbc6d1fcd"
      define_method(:install) do
        bin.install "devmachine"
        bin.install_symlink bin/"devmachine" => "advm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mydevmachine/devmachine/releases/download/v0.7.27/devmachine_0.7.27_linux_arm64.tar.gz"
      sha256 "0bcc82dc4cd70f879fbfd0295b830e124f5cb699b0f3390165e12144c282b02d"
      define_method(:install) do
        bin.install "devmachine"
        bin.install_symlink bin/"devmachine" => "advm"
      end
    end
  end

  def caveats
    <<~EOS
      Teach your coding agent devmachine (Claude Code, Codex, and others):
        devmachine skills add
      Get started: https://mydevmachine.sh/getting-started/
    EOS
  end

  test do
    system "#{bin}/devmachine", "version"
  end
end
